Linear Algebra Operations For Machine Learning

Core Operations
- Scalar Operations
- Vector Operations
- Matrix Operations
- Tensor Operations

ML-Critical Extensions
- Norms & Distances
- Similarity (Cosine, Dot)
- Linear Transformations (Ax)
- Projection

Advanced (but important)
- Matrix Decompositions
- Eigenvalues & Eigenvectors
- Rank
- Determinant & Inverse

In [90]:
# import

import math
import numpy as np
import torch as th
import tensorflow as tf
import math

In [91]:
# Core Operations
# 1. Scalar Operations
# 2. Vector Operations
# 3. Matrix Operations
# 4. Tensor Operations

1. Scalar Operations (very simple)

In [92]:

# A scalar is a single number.

# Base Python scalars
a = 5
b = 2

add = a + b
mul = a * b
div = a / b
power = (a - b) ** 2

# Print: add, mul, div, power
print("Python:", add, mul, div, power)

Python: 7 10 2.5 9


In [93]:
# NumPy scalars (0-d arrays) behave like scalars
an = np.array(5.0)
bn = np.array(2.0)

add_n = an + bn
mul_n = an * bn
div_n = an / bn
power_n = (an - bn) ** 2

# Print the same operations (NumPy)
print("NumPy:", float(add_n), float(mul_n), float(div_n), float(power_n))

NumPy: 7.0 10.0 2.5 9.0


In [94]:
# PyTorch scalars (0-d tensors)
at = th.tensor(5.0)
bt = th.tensor(2.0)

add_t = at + bt
mul_t = at * bt
div_t = at / bt
power_t = (at - bt) ** 2

# Print the same operations (PyTorch)
print("PyTorch:", add_t.item(), mul_t.item(), div_t.item(), power_t.item())

PyTorch: 7.0 10.0 2.5 9.0


In [95]:
# TensorFlow scalars (0-d tensors)
af = tf.constant(5.0)
bf = tf.constant(2.0)

add_f = af + bf
mul_f = af * bf
div_f = af / bf
power_f = (af - bf) ** 2

# Print the same operations (TensorFlow)
print("TensorFlow:", float(add_f.numpy()), float(mul_f.numpy()), float(div_f.numpy()), float(power_f.numpy()))

TensorFlow: 7.0 10.0 2.5 9.0


2. Vector Operations in ML - A vector is an ordered list of numbers (1D).

In [96]:
# Vector Operations in ML (extended with real roles)

# Base Python vectors
v = [1, 2, 3]
w = [4, 5, 6]

# 1. Addition (element-wise)
add = [vi + wi for vi, wi in zip(v, w)]

# 2. Scalar Multiplication
k = 0.1
scaled = [k * vi for vi in v]

# 3. Dot Product (very important)
dot = sum(vi * wi for vi, wi in zip(v, w))

# 4. Norm (vector length)
norm = sum(vi**2 for vi in v) ** 0.5

# 5. Unit Vector (normalization)
unit_vector = [vi / norm for vi in v]

print(f"Addition Vector: {add}")
print(f"Scalar Manipation: {scaled}")
print(f"Dot Vector: {dot}" )
print(f"Original Vector: {v}")
print(f"Norm (Magnitude): {norm:.4f}")
print(f"Unit Vector: {unit_vector}")

# Verification: the norm of a unit vector should be 1
print(f"Verification: {sum(ui**2 for ui in unit_vector)**0.5:.1f}")


Addition Vector: [5, 7, 9]
Scalar Manipation: [0.1, 0.2, 0.30000000000000004]
Dot Vector: 32
Original Vector: [1, 2, 3]
Norm (Magnitude): 3.7417
Unit Vector: [0.2672612419124244, 0.5345224838248488, 0.8017837257372732]
Verification: 1.0


In [97]:
# NumPy

# Define vectors as NumPy arrays
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

# 1. Addition
add = v + w
# 2. Scalar Multiplication
scaled = 0.1 * v
# 3. Dot Product
dot = np.dot(v, w)
# 4. Norm (L2 Norm)
norm = np.linalg.norm(v)
# 5. Unit Vector (Normalization)
unit_vector = v / norm

print(f"NumPy Addition: {add}")
print(f"NumPy Scalar Multiplication: {scaled}")
print(f"NumPy Dot Product: {dot}")
print(f"NumPy Norm: {norm:.4f}")
print(f"NumPy Unit Vector: {unit_vector}")


NumPy Addition: [5 7 9]
NumPy Scalar Multiplication: [0.1 0.2 0.3]
NumPy Dot Product: 32
NumPy Norm: 3.7417
NumPy Unit Vector: [0.26726124 0.53452248 0.80178373]


In [98]:
# PyTorch

# Define vectors as Tensors
v = th.tensor([1.0, 2.0, 3.0])
w = th.tensor([4.0, 5.0, 6.0])

# 1. Addition
add = v + w

# 2. Scalar Multiplication
scaled = 0.1 * v

# 3. Dot Product
dot = th.dot(v, w)

# 4. Norm
norm = th.norm(v)

# 5. Unit Vector
unit_vector = v / norm

print(f"PyTorch Addition: {add.tolist()}")
print(f"PyTorch Scalar Multiplication: {scaled.tolist()}")
print(f"PyTorch Dot Product: {dot.item()}")
print(f"PyTorch Norm: {norm.item():.4f}")
print(f"PyTorch Unit Vector: {unit_vector.tolist()}")


PyTorch Addition: [5.0, 7.0, 9.0]
PyTorch Scalar Multiplication: [0.10000000149011612, 0.20000000298023224, 0.30000001192092896]
PyTorch Dot Product: 32.0
PyTorch Norm: 3.7417
PyTorch Unit Vector: [0.26726123690605164, 0.5345224738121033, 0.8017836809158325]


In [99]:
# TensorFlow

# Define vectors as Tensors
v = tf.constant([1.0, 2.0, 3.0])
w = tf.constant([4.0, 5.0, 6.0])

# 1. Addition
add = tf.add(v, w)

# 2. Scalar Multiplication
scaled = v * 0.1

# 3. Dot Product
dot = tf.reduce_sum(tf.multiply(v, w))

# 4. Norm
norm = tf.norm(v)

# 5. Unit Vector
unit_vector = v / norm

print(f"TF Addition: {add.numpy()}")
print(f"TF Scalar Multiplication: {scaled.numpy()}")
print(f"TF Dot Product: {dot.numpy()}")
print(f"TF Norm: {norm.numpy():.4f}")
print(f"TF Unit Vector: {unit_vector.numpy()}")


TF Addition: [5. 7. 9.]
TF Scalar Multiplication: [0.1 0.2 0.3]
TF Dot Product: 32.0
TF Norm: 3.7417
TF Unit Vector: [0.26726124 0.5345225  0.8017837 ]


Vectors are used in real ML

In [100]:
# Vector Operations in ML (extended with real roles) - Full Flow Example (simple ML step)
# A vector is a 1D ordered list of numbers.
# These are just meanings/roles, not math:
# •	Feature vector → input data
# •	Weight vector → model parameters
# •	Embedding → meaning representation
# •	Gradient vector → update direction

# Step 1: Input (feature vector - e.g., House Size, Age)
x = np.array([2.0, 3.0])
y_true = 50.0  # target (e.g., Price)

# Step 2: Parameters (what the model learns)
w = np.array([0.1, 0.2])
b = 0.5  # bias (scalar)

# Step 3: Prediction (dot product + bias)
y_pred = np.dot(w, x) + b
print(f"Prediction: {y_pred}")

# Step 4: Loss (squared error)
loss = (y_pred - y_true) ** 2
print(f"Loss: {loss:.4f}")

# Step 5: Gradients (one per parameter)
error = y_pred - y_true

grad_w = 2 * error * x            # dL/dw
grad_b = 2 * error                # dL/db

print(f"Gradient w (vector): {grad_w}")
print(f"Gradient b (scalar): {grad_b}")

# Step 6: Update parameters (SGD)
learning_rate = 0.001  # smaller = more stable

print(f"Original Weights: {w}")
print(f"Original Bias: {b}")

# in-place update (common ML style)
w -= learning_rate * grad_w
b -= learning_rate * grad_b

print(f"Updated Weights:  {w}")
print(f"Updated Bias:  {b}")


# •	x → feature vector
# •	w → weight vector
# •	b → scalar bias
# •	np.dot(w, x) → vector operation
# •	loss → scalar
# •	grad_w → vector
# •	grad_b → scalar
# •	update rule → correct SGD

# This is exactly core ML loop.


Prediction: 1.3
Loss: 2371.6900
Gradient w (vector): [-194.8 -292.2]
Gradient b (scalar): -97.4
Original Weights: [0.1 0.2]
Original Bias: 0.5
Updated Weights:  [0.2948 0.4922]
Updated Bias:  0.5974


In [101]:
# Clean mental model
# x (vector) → input
# w (vector) → model
# b (scalar) → shift

# dot(w, x) → prediction

# error → scalar
# grad_w → vector
# grad_b → scalar

# update → learning

3. Matrix Operations - A **matrix** is a 2D array (rows × columns).

In [102]:
# Base Python Matrices (2x2 example)
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

# 1. Addition (element-wise)
add = [[A[i][j] + B[i][j] for j in range(2)] for i in range(2)]

# 2. Scalar Multiplication
k = 2
scaled = [[k * A[i][j] for j in range(2)] for i in range(2)]

# 3. Matrix Multiplication (A @ B)
matmul = [[A[i][0] * B[0][j] + A[i][1] * B[1][j] for j in range(2)] for i in range(2)]

# 4. Transpose (A^T)
transpose = [[A[j][i] for j in range(2)] for i in range(2)]

# 5. Identity (I)
identity = [[1, 0],
            [0, 1]]

# 6. Determinant det(A) for 2x2
# det([[a,b],[c,d]]) = ad - bc
a, b = A[0]
c, d = A[1]
det = a * d - b * c

# 7. Inverse A^{-1} for 2x2 (if det != 0)
# A^{-1} = (1/det) * [[d, -b], [-c, a]]
inv = [[d / det, -b / det], [-c / det, a / det]] if det != 0 else None

print(f"add (A + B): {add}")
print(f"scalar multiply (k*A): {scaled}")
print(f"matrix multiply (A @ B): {matmul}")
print(f"transpose (A^T): {transpose}")
print(f"identity (I): {identity}")
print(f"determinant det(A): {det}")
print(f"inverse A^(-1): {inv}")


add (A + B): [[6, 8], [10, 12]]
scalar multiply (k*A): [[2, 4], [6, 8]]
matrix multiply (A @ B): [[19, 22], [43, 50]]
transpose (A^T): [[1, 3], [2, 4]]
identity (I): [[1, 0], [0, 1]]
determinant det(A): -2
inverse A^(-1): [[-2.0, 1.0], [1.5, -0.5]]


In [103]:
# NumPy

A = np.array([[1, 2], [3, 4]], dtype=float)
B = np.array([[5, 6], [7, 8]], dtype=float)

# 1. Addition
add = A + B

# 2. Scalar Multiply
k = 10
scaled = k * A

# 3. Matrix Multiply
matmul = A @ B

# 4. Transpose
transpose = A.T

# 5. Identity
identity = np.eye(2)

# 6. Inverse
inv = np.linalg.inv(A)

# 7. Determinant
det = np.linalg.det(A)

print(f"add (A + B):\n{add}")
print(f"scalar multiply (k*A):\n{scaled}")
print(f"matrix multiply (A @ B):\n{matmul}")
print(f"transpose (A^T):\n{transpose}")
print(f"identity (I):\n{identity}")
print(f"inverse A^(-1):\n{inv}")
print(f"determinant det(A): {det:.2f}")


add (A + B):
[[ 6.  8.]
 [10. 12.]]
scalar multiply (k*A):
[[10. 20.]
 [30. 40.]]
matrix multiply (A @ B):
[[19. 22.]
 [43. 50.]]
transpose (A^T):
[[1. 3.]
 [2. 4.]]
identity (I):
[[1. 0.]
 [0. 1.]]
inverse A^(-1):
[[-2.   1. ]
 [ 1.5 -0.5]]
determinant det(A): -2.00


In [104]:
# PyTorch

A = th.tensor([[1.0, 2.0], [3.0, 4.0]])
B = th.tensor([[5.0, 6.0], [7.0, 8.0]])

# 1. Addition
add = A + B

# 2. Scalar Multiplication
k = 10.0
scaled = k * A

# 3. Matrix Multiplication
matmul = th.matmul(A, B)  # or A @ B

# 4. Transpose
transpose = A.T

# 5. Identity
identity = th.eye(2)

# 6. Inverse
inv = th.inverse(A)

# 7. Determinant
det = th.det(A)

print(f"add (A + B):\n{add}")
print(f"scalar multiply (k*A):\n{scaled}")
print(f"matrix multiply (A @ B):\n{matmul}")
print(f"transpose (A^T):\n{transpose}")
print(f"identity (I):\n{identity}")
print(f"inverse A^(-1):\n{inv}")
print(f"determinant det(A): {det.item():.2f}")


add (A + B):
tensor([[ 6.,  8.],
        [10., 12.]])
scalar multiply (k*A):
tensor([[10., 20.],
        [30., 40.]])
matrix multiply (A @ B):
tensor([[19., 22.],
        [43., 50.]])
transpose (A^T):
tensor([[1., 3.],
        [2., 4.]])
identity (I):
tensor([[1., 0.],
        [0., 1.]])
inverse A^(-1):
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
determinant det(A): -2.00


In [105]:
# TensorFlow

A = tf.constant([[1.0, 2.0], [3.0, 4.0]])
B = tf.constant([[5.0, 6.0], [7.0, 8.0]])

# 1. Addition
add = tf.add(A, B)

# 2. Scalar Multiplication
k = 10.0
scaled = k * A

# 3. Matrix Multiplication
matmul = tf.matmul(A, B)

# 4. Transpose
transpose = tf.transpose(A)

# 5. Identity
identity = tf.eye(2)

# 6. Inverse
inv = tf.linalg.inv(A)

# 7. Determinant
det = tf.linalg.det(A)

print(f"add (A + B):\n{add.numpy()}")
print(f"scalar multiply (k*A):\n{scaled.numpy()}")
print(f"matrix multiply (A @ B):\n{matmul.numpy()}")
print(f"transpose (A^T):\n{transpose.numpy()}")
print(f"identity (I):\n{identity.numpy()}")
print(f"inverse A^(-1):\n{inv.numpy()}")
print(f"determinant det(A): {det.numpy():.2f}")


add (A + B):
[[ 6.  8.]
 [10. 12.]]
scalar multiply (k*A):
[[10. 20.]
 [30. 40.]]
matrix multiply (A @ B):
[[19. 22.]
 [43. 50.]]
transpose (A^T):
[[1. 3.]
 [2. 4.]]
identity (I):
[[1. 0.]
 [0. 1.]]
inverse A^(-1):
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]
determinant det(A): -2.00


Matrix in ML (simple example with steps)

In [106]:
# Matrix Operations in ML (meanings of common symbols)
# In ML, matrices play various roles depending on the context:
# • X → feature matrix (input data, each row is a sample, each column is a feature)
# • W → weight matrix (model parameters)
# • b → bias (offset vector or matrix)
# • Y → output (predicted values, labels, or logits)
# • A → activation (result after applying activation function)
# • grad → gradients (matrix/tensor representing derivatives for learning)
# • loss → optimization target (scalar or tensor representing error to be minimized)

# Step 1: Input (X → Feature Matrix)
# 3 samples (rows), 2 features each (columns)
# Features could be [Area, Rooms]
X = np.array([[2.0, 3.0], 
              [1.5, 2.0], 
              [4.0, 5.0]])

# Ground truth for the 3 samples (3 target prices)
Y_true = np.array([[50.0], [35.0], [90.0]])

# Step 2: Parameters (W → Weight Matrix, b → Bias)
# W connects 2 inputs to 1 output neuron
W = np.array([[0.1], 
              [0.2]])
b = 0.5

# Step 3: Prediction (Y → Linear Output)
# Y = X @ W + b
# Matrix multiplication handles all 3 samples at once!
Y = np.dot(X, W) + b
print(f"Linear Output (Y):\n{Y}")

# Step 4: Activation (A → Non-linearity)
# Simple ReLU activation: max(0, Y)
A = np.maximum(0, Y)
print(f"Activation (A):\n{A}")

# Step 5: Loss (Optimization Target)
# Mean Squared Error across the batch
loss = np.mean((A - Y_true)**2)
print(f"Batch Loss: {loss:.4f}")

# Step 6: Gradients (grad → Direction)
# Simplified gradient for demonstration
error = A - Y_true
grad_W = np.dot(X.T, error) / X.shape[0] # Average gradient for weights
grad_b = np.mean(error)                  # Average gradient for bias

# Step 7: Update weights
lr = 0.01
W -= lr * grad_W
b -= lr * grad_b

print(f"Updated Weights (W):\n{W}")
print(f"Updated Bias (b): {b:.4f}")


Linear Output (Y):
[[1.3 ]
 [1.05]
 [1.9 ]]
Activation (A):
[[1.3 ]
 [1.05]
 [1.9 ]]
Batch Loss: 3761.9675
Updated Weights (W):
[[1.76908333]
 [2.38166667]]
Updated Bias (b): 1.0692


In [107]:
# Matrix (Batch) Training Loop — same logic as vector, but for many samples
# 1. Data: 4 samples (rows), 2 features each (columns)
X = np.array([
    [2.0, 3.0], 
    [1.0, 1.0], 
    [4.0, 2.0], 
    [5.0, 5.0]
])

# 2. Target: The "real" prices for these 4 samples
Y_true = np.array([
    [13.0], 
    [5.0], 
    [14.0], 
    [25.0]
])

# 3. Parameters: Start with random weights and zero bias
W = np.random.randn(2, 1) 
b = 0.0

learning_rate = 0.01
epochs = 100

print("Starting Training...")
for epoch in range(epochs):
    # --- FORWARD PASS (Matrix Math) ---
    # Prediction: Y = XW + b
    Y_pred = np.dot(X, W) + b
    
    # Calculate Loss (Mean Squared Error)
    loss = np.mean((Y_pred - Y_true)**2)
    
    # --- BACKWARD PASS (Gradients) ---
    # How much did we miss?
    error = Y_pred - Y_true
    
    # Gradient of W: (X_transpose @ error) / batch_size
    grad_W = np.dot(X.T, error) / X.shape[0]
    
    # Gradient of b: average of the errors
    grad_b = np.mean(error)
    
    # --- UPDATE (Optimizer step) ---
    W -= learning_rate * grad_W
    b -= learning_rate * grad_b
    
    if epoch % 10 == 0:
        print(f"Epoch {epoch}: Loss = {loss:.4f}")

print("-" * 30)
print(f"Final Weights (W):\n{W}")
print(f"Final Bias (b): {b:.4f}")

# Test with a new sample [3.0, 3.0]
test_sample = np.array([[3.0, 3.0]])
prediction = np.dot(test_sample, W) + b
print(f"Prediction for [3.0, 3.0]: {prediction[0][0]:.2f}")


Starting Training...
Epoch 0: Loss = 155.7973
Epoch 10: Loss = 1.6023
Epoch 20: Loss = 0.3396
Epoch 30: Loss = 0.2970
Epoch 40: Loss = 0.2676
Epoch 50: Loss = 0.2413
Epoch 60: Loss = 0.2179
Epoch 70: Loss = 0.1969
Epoch 80: Loss = 0.1781
Epoch 90: Loss = 0.1613
------------------------------
Final Weights (W):
[[2.2278937 ]
 [2.62370179]]
Final Bias (b): 0.4336
Prediction for [3.0, 3.0]: 14.99


4. Tensor Operations

In [108]:
# ML Basic Topics

# Vector section: Cosine Similarity
# Matrix section: Element-wise vs Matrix Multiplication difference | Attention basic idea

# 1. Broadcasting  
# 2. Indexing / Slicing  
# 3. Reshape  
# 4. Squeeze / Unsqueeze  
# 5. Concatenate / Stack  
# 6. Masking  
# 7. Autograd  
# 8. Attention (basic idea)  

In [109]:
# What is Cosine Similarity ?
# Unlike Euclidean Distance (which measures the physical distance between points), Cosine Similarity measures the angle between two vectors.

# In Machine Learning, this is very important because it tells us if two vectors are pointing in the same direction, even if one is much "longer" than the other.

# 1.0: The vectors are identical in direction (angle = 0°).
# 0.0: The vectors are orthogonal (perpendicular, angle = 90°).
# -1.0: The vectors are pointing in opposite directions (angle = 180°).
# The Formula: $$\text{Similarity} = \frac{A \cdot B}{||A|| \times ||B||}$$ (Dot Product divided by the product of their Magnitudes)

import torch.nn.functional as F

# Define the same vectors for all tests
v1_list, v2_list = [1, 2, 3], [1, 2, 4]

print("--- Cosine Similarity Comparison ---")

# 1. Base Python Logic
dot = sum(a*b for a, b in zip(v1_list, v2_list))
norm1 = sum(a**2 for a in v1_list)**0.5
norm2 = sum(b**2 for b in v2_list)**0.5
sim_python = dot / (norm1 * norm2)
print(f"Base Python: {sim_python:.4f}")

# 2. NumPy Implementation
v1_np, v2_np = np.array(v1_list), np.array(v2_list)
sim_numpy = np.dot(v1_np, v2_np) / (np.linalg.norm(v1_np) * np.linalg.norm(v2_np))
print(f"NumPy:       {sim_numpy:.4f}")

# 3. PyTorch Implementation
v1_pt, v2_pt = th.tensor([v1_list], dtype=th.float32), th.tensor([v2_list], dtype=th.float32)
sim_pytorch = F.cosine_similarity(v1_pt, v2_pt)
print(f"PyTorch:     {sim_pytorch.item():.4f}")

# 4. TensorFlow Implementation
v1_tf, v2_tf = tf.constant(v1_list, dtype=tf.float32), tf.constant(v2_list, dtype=tf.float32)
cosine_loss = tf.keras.losses.CosineSimilarity()
# TF calculates loss (negative similarity), so we flip it back
sim_tf = -cosine_loss(v1_tf, v2_tf)
print(f"TensorFlow:  {sim_tf.numpy():.4f}")

print("-" * 37)
print("Result: All libraries give the same math result!")




--- Cosine Similarity Comparison ---
Base Python: 0.9915
NumPy:       0.9915
PyTorch:     0.9915
TensorFlow:  0.9915
-------------------------------------
Result: All libraries give the same math result!


In [110]:
# Define matrices for testing
A_list = [[1, 2], [3, 4]]
B_list = [[5, 6], [7, 8]]

print("--- 1. Element-wise (*) vs Matrix Multiplication (@) ---")

# --- NumPy ---
A_np, B_np = np.array(A_list), np.array(B_list)
print(f"NumPy Element-wise:\n{A_np * B_np}")
print(f"NumPy Matrix Mult (@):\n{A_np @ B_np}")

# --- PyTorch ---
A_pt, B_pt = th.tensor(A_list), th.tensor(B_list)
print(f"\nPyTorch Element-wise:\n{A_pt * B_pt}")
print(f"PyTorch Matrix Mult (matmul):\n{th.matmul(A_pt, B_pt)}")

# --- TensorFlow ---
A_tf, B_tf = tf.constant(A_list), tf.constant(B_list)
print(f"\nTF Element-wise:\n{(A_tf * B_tf).numpy()}")
print(f"TF Matrix Mult (matmul):\n{tf.matmul(A_tf, B_tf).numpy()}")

print("\n" + "="*40)

print("--- 2. Basic Attention Intuition ---")
# Attention is basically: Matrix Mult of Queries(Q) and Keys(K)

# 3 Words, 2 Features each
Q = np.array([[1, 0], [0, 1], [1, 1]]) # Queries
K = np.array([[1, 0], [0, 1], [0, 0]]) # Keys

# The Matrix Multiplication (@) calculates the relationship between every word
# This 'Map' tells the model which words are similar
attention_map = Q @ K.T

print(f"Attention Map (Similarity Matrix):\n{attention_map}")
print("\nInterpretation: Higher numbers = Higher importance/attention.")


--- 1. Element-wise (*) vs Matrix Multiplication (@) ---
NumPy Element-wise:
[[ 5 12]
 [21 32]]
NumPy Matrix Mult (@):
[[19 22]
 [43 50]]

PyTorch Element-wise:
tensor([[ 5, 12],
        [21, 32]])
PyTorch Matrix Mult (matmul):
tensor([[19, 22],
        [43, 50]])

TF Element-wise:
[[ 5 12]
 [21 32]]
TF Matrix Mult (matmul):
[[19 22]
 [43 50]]

--- 2. Basic Attention Intuition ---
Attention Map (Similarity Matrix):
[[1 0 0]
 [0 1 0]
 [1 1 0]]

Interpretation: Higher numbers = Higher importance/attention.


In [111]:
# 1. Broadcasting
# Why: It allows you to perform math on arrays with different shapes without manually looping. For example, adding a bias b to a whole matrix of predictions.

# Matrix (3x2)
A = np.array([[1, 1], [2, 2], [3, 3]])
# Row Vector (1x2)
v = np.array([10, 20])

# NumPy "stretches" v to match the rows of A automatically
result = A + v 

print(f"Original A:\n{A}")
print(f"Vector v: {v}")
print(f"Broadcasting Result (A + v):\n{result}")


Original A:
[[1 1]
 [2 2]
 [3 3]]
Vector v: [10 20]
Broadcasting Result (A + v):
[[11 21]
 [12 22]
 [13 23]]


In [112]:
# 2. Indexing / Slicing
# Why: Used to grab specific features, specific samples in a batch, or to "crop" data.

data = th.tensor([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])

# [row, column]
first_row = data[0, :]      # Get first row
last_column = data[:, -1]   # Get last column
sub_matrix = data[0:2, 1:3] # Get top-right 2x2 square

print(f"First Row: {first_row}")
print(f"Sub-matrix (Slice):\n{sub_matrix}")


First Row: tensor([10, 20, 30])
Sub-matrix (Slice):
tensor([[20, 30],
        [50, 60]])


In [113]:
# 3. Reshape
# Why: One of the most used tools. Used to convert a 2D image (28x28) into a 1D vector (784) for a neural network.

# A flat vector of 6 elements
v = np.array([1, 2, 3, 4, 5, 6])
# Change shape to 2 rows, 3 columns
matrix = v.reshape(2, 3)
# -1 means "calculate this dimension automatically"
auto_matrix = v.reshape(3, -1) 
print(f"Reshaped to 2x3:\n{matrix}")
print(f"Reshaped to 3x2 (auto):\n{auto_matrix}")

Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
Reshaped to 3x2 (auto):
[[1 2]
 [3 4]
 [5 6]]


In [114]:
# 4. Squeeze / Unsqueeze
# Why: Very important for batches. If you have a single image, you often need to "Unsqueeze" it to turn shape (28, 28) into (1, 28, 28) so the model sees a "Batch of 1."

x = th.tensor([1, 2, 3]) # Shape (3)

# Add a dimension at index 0 -> Shape (1, 3)
x_un = x.unsqueeze(0) 

# Remove all dimensions of size 1
x_sq = x_un.squeeze()

print(f"Original Shape: {x.shape}")
print(f"Unsqueezed Shape: {x_un.shape}")
print(f"Squeezed Shape: {x_sq.shape}")


Original Shape: torch.Size([3])
Unsqueezed Shape: torch.Size([1, 3])
Squeezed Shape: torch.Size([3])


In [115]:
# 5. Concatenate / Stack
# Why: Used to combine features from different sources or to join several images into one batch.

A = np.array([[1, 2]])
B = np.array([[3, 4]])

# Concatenate: Joins along existing axis (Makes it 1x4)
conc = np.concatenate((A, B), axis=1)

# Stack: Joins along a NEW axis (Makes it 2x2)
stk = np.stack((A, B), axis=0)

print(f"Concatenated:\n{conc}")
print(f"Stacked:\n{stk}")


Concatenated:
[[1 2 3 4]]
Stacked:
[[[1 2]]

 [[3 4]]]


In [116]:
# 6. Masking
# Why: Used to filter data. In Attention, we use masks to hide "future" words so the model can't cheat.

data = th.tensor([1, -5, 10, -2, 4])

# Create a boolean mask
mask = data > 0

# Apply mask: only keep positive values
filtered_data = data[mask]

# Replace values: set all negatives to 0 (This is how ReLU works!)
data[data < 0] = 0

print(f"Boolean Mask: {mask}")
print(f"Filtered: {filtered_data}")
print(f"Zeroed out negatives: {data}")


Boolean Mask: tensor([ True, False,  True, False,  True])
Filtered: tensor([ 1, 10,  4])
Zeroed out negatives: tensor([ 1,  0, 10,  0,  4])


In [117]:
# 7. Autograd (Automatic Gradients)
# Why: This is the magic of PyTorch/TF. You don't have to calculate derivatives yourself; the library tracks the math and does it for you.

# requires_grad=True tells PyTorch to track this variable
x = th.tensor(2.0, requires_grad=True)

# Define a function: y = x^3
y = x**3

# Calculate the gradient (Derivative)
y.backward()

# dy/dx at x=2 is 3*(x^2) = 3*(2^2) = 12
print(f"Value of x: {x}")
print(f"Value of y (x^3): {y}")
print(f"Gradient (dy/dx): {x.grad}")


Value of x: 2.0
Value of y (x^3): 8.0
Gradient (dy/dx): 12.0


In [118]:
# 8. Attention (Scaling Dot-Product)
# Why: The final piece. This shows how $Q$, $K$, and $V$ work together using everything we learned above.

import torch.nn.functional as F

# 1. Queries, Keys, Values
Q = th.tensor([[1.0, 0.0], [0.0, 1.0]])
K = th.tensor([[1.0, 0.0], [0.0, 1.0]])
V = th.tensor([[10.0, 20.0], [30.0, 40.0]])

# 2. Calculate Attention Scores (Matrix Mult)
scores = th.matmul(Q, K.T)

# 3. Softmax (turns scores into probabilities that sum to 1)
weights = F.softmax(scores, dim=-1)

# 4. Final Output (weighted sum of Values)
output = th.matmul(weights, V)

print(f"Attention Weights:\n{weights}")
print(f"Final Attention Output:\n{output}")


Attention Weights:
tensor([[0.7311, 0.2689],
        [0.2689, 0.7311]])
Final Attention Output:
tensor([[15.3788, 25.3788],
        [24.6212, 34.6212]])
