Linear Algebra Operations For Machine Learning

Core Operations
- Scalar Operations
- Vector Operations
- Matrix Operations
- Tensor Operations

ML-Critical Extensions
- Norms & Distances
- Similarity (Cosine, Dot)
- Linear Transformations (Ax)
- Projection

Advanced (but important)
- Matrix Decompositions
- Eigenvalues & Eigenvectors
- Rank
- Determinant & Inverse

In [ ]:
# import

import numpy as np
import torch as th
import tensorflow as tf
import math

In [ ]:
# Core Operations
# 1. Scalar Operations
# 2. Vector Operations
# 3. Matrix Operations
# 4. Tensor Operations

# ML-Critical Extensions
# 5. Norms & Distances
# 6. Similarity (Cosine, Dot)
# 7. Linear Transformations (Ax)
# 8. Projection

# Advanced (but important)
# 9. Matrix Decompositions
# 10. Eigenvalues & Eigenvectors
# 11. Rank
# 12. Determinant & Inverse

In [ ]:
# 1. Scalar Operations in ML - A scalar in ML is one number.

# Base Python
# scalar = one number
b = 2.0                 # bias (scalar)
x = 3.0                 # one feature value (scalar)
w = 0.5                 # weight (scalar)

z = w * x + b           # linear model output (scalar)
print(z)                # 3.5

lr = 0.1                # learning rate (scalar)
theta = 1.0             # parameter (scalar)
grad = 0.6              # dL/dtheta (scalar)

theta = theta - lr * grad
print(theta)            # 0.94


# Numpy
import numpy as np

y = np.array([3.0, 5.0, 2.0])
yhat = np.array([2.5, 4.0, 2.2])

mse = np.mean((y - yhat) ** 2)   # scalar loss
print(mse)

p = 0.2
keep_prob = 1.0 - p              # scalar hyperparameter
print(keep_prob)


# PyTorch
import torch

y = torch.tensor([3.0, 5.0, 2.0])
yhat = torch.tensor([2.5, 4.0, 2.2])

loss = torch.mean((y - yhat) ** 2)  # scalar tensor (0-dim)
print(loss.item())                  # Python scalar

x = torch.tensor(2.0, requires_grad=True)  # scalar parameter
loss2 = (x - 5) ** 2                        # scalar loss
loss2.backward()
print(x.grad.item())                        # scalar gradient


# TensorFlow
import tensorflow as tf

y = tf.constant([3.0, 5.0, 2.0])
yhat = tf.constant([2.5, 4.0, 2.2])

mse = tf.reduce_mean(tf.square(y - yhat))  # scalar tensor
print(float(mse.numpy()))

x = tf.Variable(2.0)  # scalar parameter
with tf.GradientTape() as tape:
    loss = (x - 5.0) ** 2                  # scalar loss
grad = tape.gradient(loss, x)
print(float(grad.numpy()))                 # scalar gradient

In [ ]:
# 2. Vector Operations in ML - A vector is an ordered list of numbers (1D).

# In ML, vectors commonly represent:
# - feature vectors (one data point)
# - weight vectors
# - embeddings
# - gradients

# Base Python (lists)
a = [1, 2, 3]
b = [10, 20, 30]

# element-wise addition
add = [ai + bi for ai, bi in zip(a, b)]
print("a + b =", add)  # [11, 22, 33]

# element-wise multiplication (mask/gate)
mask = [1, 0, 1]
masked = [ai * mi for ai, mi in zip(a, mask)]
print("a * mask =", masked)  # [1, 0, 3]

# dot product (linear score)
w = [0.2, -0.5, 1.0]
x = [3, 4, 2]
dot = sum(wi * xi for wi, xi in zip(w, x))
print("w·x =", dot)  # 0.6


# NumPy (preferred for vector math)
import numpy as np

va = np.array([1.0, 2.0, 3.0])
vb = np.array([10.0, 20.0, 30.0])

print("va + vb =", va + vb)          # element-wise addition
print("va * vb =", va * vb)          # element-wise multiplication
print("va·vb =", va @ vb)            # dot product

# L2 norm (magnitude)
print("||va|| =", np.linalg.norm(va))

# cosine similarity
cos_sim = (va @ vb) / (np.linalg.norm(va) * np.linalg.norm(vb))
print("cos(va, vb) =", cos_sim)

# broadcasting: scale every element by a scalar
print("2 * va =", 2 * va)


# PyTorch (vectors as 1D tensors)
import torch

ta = torch.tensor([1.0, 2.0, 3.0])
tb = torch.tensor([10.0, 20.0, 30.0])

print("ta + tb =", ta + tb)
print("ta * tb =", ta * tb)
print("ta·tb =", torch.dot(ta, tb))
print("||ta|| =", torch.linalg.norm(ta))


# TensorFlow (vectors as 1D tensors)
import tensorflow as tf

fa = tf.constant([1.0, 2.0, 3.0])
fb = tf.constant([10.0, 20.0, 30.0])

print("fa + fb =", (fa + fb).numpy())
print("fa * fb =", (fa * fb).numpy())
print("fa·fb =", tf.tensordot(fa, fb, axes=1).numpy())
print("||fa|| =", tf.linalg.norm(fa).numpy())





a + b = [11, 22, 33]
a * mask = [1, 0, 3]
w·x = 0.6000000000000001
va + vb = [11. 22. 33.]
va * vb = [10. 40. 90.]
va·vb = 140.0
||va|| = 3.7416573867739413
cos(va, vb) = 1.0
2 * va = [2. 4. 6.]
ta + tb = tensor([11., 22., 33.])
ta * tb = tensor([10., 40., 90.])
ta·tb = tensor(140.)
||ta|| = tensor(3.7417)
fa + fb = [11. 22. 33.]
fa * fb = [10. 40. 90.]
fa·fb = 140.0
||fa|| = 3.7416575


In [ ]:
# Key ML Applications

# 1. Linear Models & Neural Networks
# Forward pass in a linear layer: z = Wx + b
x = np.array([1.0, 2.0, 3.0])           # input vector (3 features)
W = np.array([[0.1, 0.2, 0.3],          # weight matrix (2x3)
              [0.4, 0.5, 0.6]])
b = np.array([0.1, -0.2])               # bias vector (2 outputs)

z = W @ x + b   # Matrix-vector product + vector addition → output vector

# 2. Gradient Updates
# Stochastic Gradient Descent update (vectorized)
weights = np.array([0.5, -0.3, 0.8])
gradients = np.array([0.02, -0.01, 0.05])
learning_rate = 0.01  # scalar

weights = weights - learning_rate * gradients  # Element-wise scalar-vector op

# 3. Similarity & Embeddings
from numpy.linalg import norm

def cosine_similarity(a, b):
    return np.dot(a, b) / (norm(a) * norm(b))

# Compare two word embeddings
vec_cat = np.array([0.9, 0.1, 0.3])
vec_dog = np.array([0.8, 0.2, 0.4])

similarity = cosine_similarity(vec_cat, vec_dog)  # ≈ 0.98 → very similar

# 4. Normalization (Batch/Layer Norm)
# L2 normalization of a feature vector
v = np.array([3.0, 4.0])
v_normalized = v / norm(v)  # → [0.6, 0.8], ‖v_normalized‖ = 1.0

In [16]:
# 3. Matrix Operations in ML - A matrix is a 2D grid of numbers (rows x columns).

# In ML, matrices commonly represent:
# - weights in a linear layer (W)
# - a batch of data (X): each row is one example
# - covariance/correlation matrices
# - attention score matrices (QK^T)

# Make this cell runnable even if the global import cell wasn't executed.
import numpy as np
import torch
import tensorflow as tf

# Base Python (lists of lists)
A = [[1, 2],
     [3, 4]]
B = [[10, 20],
     [30, 40]]

# matrix addition (element-wise)
A_plus_B = [[A[i][j] + B[i][j] for j in range(2)] for i in range(2)]
print("A + B =", A_plus_B)  # [[11, 22], [33, 44]]

# scalar * matrix
alpha = 0.5
alphaA = [[alpha * A[i][j] for j in range(2)] for i in range(2)]
print("alpha * A =", alphaA)  # [[0.5, 1.0], [1.5, 2.0]]

# matrix transpose
AT = [[A[j][i] for j in range(2)] for i in range(2)]
print("A^T =", AT)  # [[1, 3], [2, 4]]

# matrix multiplication (2x2)
C = [
    [A[0][0]*B[0][0] + A[0][1]*B[1][0], A[0][0]*B[0][1] + A[0][1]*B[1][1]],
    [A[1][0]*B[0][0] + A[1][1]*B[1][0], A[1][0]*B[0][1] + A[1][1]*B[1][1]],
]
print("A @ B =", C)


# NumPy (preferred for matrices)
A = np.array([[1., 2.],
              [3., 4.]])
B = np.array([[10., 20.],
              [30., 40.]])

print("A + B =\n", A + B)
print("alpha * A =\n", 0.5 * A)
print("A @ B =\n", A @ B)      # matrix multiplication
print("A.T =\n", A.T)          # transpose

# element-wise ops (not matrix multiply)
print("A * B (element-wise) =\n", A * B)
print("exp(A) (element-wise) =\n", np.exp(A))

# trace and determinant
print("tr(A) =", np.trace(A))
print("det(A) =", np.linalg.det(A))

# inverse / pseudo-inverse
print("A^{-1} =\n", np.linalg.inv(A))
print("pinv(A) =\n", np.linalg.pinv(A))

# SVD: A = U S V^T (used in PCA / low-rank approximation)
U, S, Vt = np.linalg.svd(A)
print("S (singular values) =", S)

# simple low-rank approximation with k=1
k = 1
A_rank1 = (U[:, :k] * S[:k]) @ Vt[:k, :]
print("rank-1 approx(A) =\n", A_rank1)


# PyTorch
TA = torch.tensor([[1., 2.],
                   [3., 4.]])
TB = torch.tensor([[10., 20.],
                   [30., 40.]])

print("TA + TB =\n", TA + TB)
print("0.5 * TA =\n", 0.5 * TA)
print("TA @ TB =\n", TA @ TB)
print("TA.T =\n", TA.T)
print("TA * TB (element-wise) =\n", TA * TB)
print("trace(TA) =", torch.trace(TA))
print("det(TA) =", torch.det(TA))
print("inv(TA) =\n", torch.linalg.inv(TA))
print("pinv(TA) =\n", torch.linalg.pinv(TA))


# TensorFlow
FA = tf.constant([[1., 2.],
                  [3., 4.]])
FB = tf.constant([[10., 20.],
                  [30., 40.]])

print("FA + FB =\n", (FA + FB).numpy())
print("0.5 * FA =\n", (0.5 * FA).numpy())
print("FA @ FB =\n", tf.matmul(FA, FB).numpy())
print("transpose(FA) =\n", tf.transpose(FA).numpy())
print("FA * FB (element-wise) =\n", (FA * FB).numpy())

# trace / determinant
print("trace(FA) =", tf.linalg.trace(FA).numpy())
print("det(FA) =", tf.linalg.det(FA).numpy())

# inverse / pseudo-inverse
print("inv(FA) =\n", tf.linalg.inv(FA).numpy())
print("pinv(FA) =\n", tf.linalg.pinv(FA).numpy())

# SVD
s, u, v = tf.linalg.svd(FA)  # FA = u @ diag(s) @ v^T
print("singular values =", s.numpy())


A + B = [[11, 22], [33, 44]]
alpha * A = [[0.5, 1.0], [1.5, 2.0]]
A^T = [[1, 3], [2, 4]]
A @ B = [[70, 100], [150, 220]]
A + B =
 [[11. 22.]
 [33. 44.]]
alpha * A =
 [[0.5 1. ]
 [1.5 2. ]]
A @ B =
 [[ 70. 100.]
 [150. 220.]]
A.T =
 [[1. 3.]
 [2. 4.]]
A * B (element-wise) =
 [[ 10.  40.]
 [ 90. 160.]]
exp(A) (element-wise) =
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
tr(A) = 5.0
det(A) = -2.0000000000000004
A^{-1} =
 [[-2.   1. ]
 [ 1.5 -0.5]]
pinv(A) =
 [[-2.   1. ]
 [ 1.5 -0.5]]
S (singular values) = [5.4649857  0.36596619]
rank-1 approx(A) =
 [[1.27357371 1.80720735]
 [2.87897923 4.08528566]]
TA + TB =
 tensor([[11., 22.],
        [33., 44.]])
0.5 * TA =
 tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
TA @ TB =
 tensor([[ 70., 100.],
        [150., 220.]])
TA.T =
 tensor([[1., 3.],
        [2., 4.]])
TA * TB (element-wise) =
 tensor([[ 10.,  40.],
        [ 90., 160.]])
trace(TA) = tensor(5.)
det(TA) = tensor(-2.)
inv(TA) =
 tensor([[-2.0000,  1.0000],
        [ 1.

In [17]:
# Key ML Applications
# 1. Batched Linear Layer (The Most Common Matrix Op)
import numpy as np

# X: (batch_size=4, input_features=3)
X = np.array([[1.0, 2.0, 0.5],
              [0.2, 1.1, 3.0],
              [4.0, 0.0, 2.1],
              [1.5, 2.5, 1.0]])

# W: (input_features=3, output_features=2)
W = np.array([[0.1, -0.2],
              [0.3,  0.4],
              [0.5, -0.1]])

# b: (output_features=2)
b = np.array([0.1, 0.0])
print(b)

# Forward pass: Z = X @ W + b  → shape (4, 2)
Z = X @ W + b
print(Z)

[0.1 0. ]
[[ 1.05  0.55]
 [ 1.95  0.1 ]
 [ 1.55 -1.01]
 [ 1.5   0.6 ]]


In [13]:
# 2. Attention Mechanism (Transformer Core)
# Q, K, V: (batch, seq_len, d_model)
# Scaled dot-product attention
def attention(Q, K, V):
    d_k = Q.shape[-1]
    scores = Q @ K.transpose(0, 2, 1) / np.sqrt(d_k)  # (batch, seq, seq)
    weights = softmax(scores, axis=-1)                 # normalize per row
    return weights @ V                                 # (batch, seq, d_model)

In [14]:
# 3. PCA via SVD (Numerically Stable)
from numpy.linalg import svd

# NOTE: If X is a torch tensor, convert to NumPy first.
# Otherwise, np.mean(X, ...) can dispatch to torch.mean(...) and raise a TypeError.
X_np = X
try:
    import torch
    if torch.is_tensor(X_np):
        X_np = X_np.detach().cpu().numpy()
except Exception:
    pass

X_np = np.asarray(X_np)

# Center data: X_centered = X - mean(X)
X_centered = X_np - X_np.mean(axis=0)

# SVD replaces eigendecomposition of covariance matrix
U, S, Vt = svd(X_centered, full_matrices=False)

# Project to top k components
k = 2
X_pca = X_centered @ Vt[:k, :].T  # (N, k)
print("X_pca shape:", X_pca.shape)

X_pca shape: (4, 2)


In [15]:
# 4. Automatic Differentiation with Matrices
import torch

W = torch.randn(3, 2, requires_grad=True)
X = torch.randn(4, 3)

Y = X @ W          # Matrix multiply
loss = Y.pow(2).sum()  # Scalar loss

loss.backward()
print(W.grad.shape)  # → torch.Size([3, 2])
# ∂L/∂W = Xᵀ @ ∂L/∂Y (chain rule for matrix derivatives)

torch.Size([3, 2])


In [ ]:
# 4. Tensor Operations in ML - A tensor is an N-dimensional array of numbers.

# Scalars are 0D, vectors are 1D, matrices are 2D, and tensors generalize to 3D+.
# Common ML shapes:
# - images: (batch, height, width, channels) or (batch, channels, height, width)
# - sequences: (batch, seq_len, dim)
# - attention: (batch, heads, seq_len, seq_len)

import numpy as np
import torch
import tensorflow as tf


# -----------------------------
# PyTorch tensor operations
# -----------------------------
# Create a 3D tensor: (batch=2, seq=3, dim=4)
X = torch.arange(2 * 3 * 4).float().reshape(2, 3, 4)
print("X shape:", X.shape)

# 1) Reshape / View
X_flat = X.view(2, -1)  # flatten last dimensions
print("X_flat shape:", X_flat.shape)

# 2) Transpose / Permute (reorder dimensions)
X_perm = X.permute(0, 2, 1)  # (batch, dim, seq)
print("X_perm shape:", X_perm.shape)

# 3) Squeeze / Unsqueeze (add/remove size-1 dims)
v = torch.tensor([1., 2., 3.])
v_unsq = v.unsqueeze(0)  # (1, 3)
print("v_unsq shape:", v_unsq.shape)
print("squeezed back:", v_unsq.squeeze(0).shape)

# 4) Concat / Stack
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[10., 20.], [30., 40.]])
cat0 = torch.cat([A, B], dim=0)     # (4, 2)
stack0 = torch.stack([A, B], dim=0) # (2, 2, 2)
print("cat dim=0 shape:", cat0.shape)
print("stack dim=0 shape:", stack0.shape)

# 5) Index / Gather (select using indices)
# Example: pick one element from each row
M = torch.tensor([[5., 6., 7.],
                  [8., 9., 10.]])
idx = torch.tensor([[2],
                    [0]])  # per-row index (shape (2,1))
gathered = M.gather(1, idx)
print("gathered:\n", gathered)

# 6) Masking
scores = torch.tensor([[0.1, 0.5, -0.2],
                       [0.0, -1.0, 2.0]])
mask = torch.tensor([[1, 1, 0],
                     [1, 0, 1]]).bool()
masked_scores = scores.masked_fill(~mask, float("-inf"))
print("masked_scores:\n", masked_scores)

# 7) Reduction (sum/mean over dims)
print("mean over seq (dim=1) shape:", X.mean(dim=1).shape)  # (batch, dim)

# 8) Batched Matmul (batch matrix multiply)
# A: (batch, n, m), B: (batch, m, p) -> (batch, n, p)
A_b = torch.randn(2, 3, 4)
B_b = torch.randn(2, 4, 5)
C_b = torch.bmm(A_b, B_b)
print("bmm output shape:", C_b.shape)

# 9) Einstein Summation (flexible contractions)
# Equivalent to batched matmul: (b,i,k) x (b,k,j) -> (b,i,j)
C_e = torch.einsum("bik,bkj->bij", A_b, B_b)
print("einsum output shape:", C_e.shape)


# -----------------------------
# TensorFlow tensor operations
# -----------------------------
X = tf.reshape(tf.range(2 * 3 * 4, dtype=tf.float32), (2, 3, 4))
print("TF X shape:", X.shape)

# reshape
X_flat = tf.reshape(X, (2, -1))
print("TF X_flat shape:", X_flat.shape)

# transpose / permute
X_perm = tf.transpose(X, perm=(0, 2, 1))
print("TF X_perm shape:", X_perm.shape)

# squeeze / expand dims
v = tf.constant([1., 2., 3.])
v_unsq = tf.expand_dims(v, axis=0)
print("TF v_unsq shape:", v_unsq.shape)
print("TF squeezed shape:", tf.squeeze(v_unsq, axis=0).shape)

# concat / stack
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[10., 20.], [30., 40.]])
cat0 = tf.concat([A, B], axis=0)
stack0 = tf.stack([A, B], axis=0)
print("TF concat shape:", cat0.shape)
print("TF stack shape:", stack0.shape)

# gather
M = tf.constant([[5., 6., 7.],
                 [8., 9., 10.]])
idx = tf.constant([[2],
                   [0]])
gathered = tf.gather(M, idx, axis=1, batch_dims=1)
print("TF gathered:\n", gathered.numpy())

# masking
scores = tf.constant([[0.1, 0.5, -0.2],
                      [0.0, -1.0, 2.0]])
mask = tf.constant([[True, True, False],
                    [True, False, True]])
masked_scores = tf.where(mask, scores, tf.constant(-np.inf, dtype=tf.float32))
print("TF masked_scores:\n", masked_scores.numpy())

# reduction
print("TF mean over seq axis=1 shape:", tf.reduce_mean(X, axis=1).shape)

# batched matmul
A_b = tf.random.normal((2, 3, 4))
B_b = tf.random.normal((2, 4, 5))
C_b = tf.matmul(A_b, B_b)
print("TF matmul output shape:", C_b.shape)

# einsum
C_e = tf.einsum("bik,bkj->bij", A_b, B_b)
print("TF einsum output shape:", C_e.shape)


In [ ]:
# Key ML Applications
# 1. Batched Data Representation
import torch

# Image batch: (batch=32, channels=3, height=28, width=28)
images = torch.randn(32, 3, 28, 28)

# Reshape for a fully connected layer: flatten spatial dims
flat = images.view(32, -1)  # → (32, 2352)

In [ ]:
# 2. Transformer Attention (Batched 3D Tensors)
# Q, K, V: (batch, seq_len, d_model) = (8, 16, 64)
Q = torch.randn(8, 16, 64)
K = torch.randn(8, 16, 64)
V = torch.randn(8, 16, 64)

# Scaled dot-product attention (batched)
scores = torch.bmm(Q, K.transpose(1, 2)) / (64 ** 0.5)  # (8, 16, 16)
attn = torch.softmax(scores, dim=-1)
output = torch.bmm(attn, V)  # (8, 16, 64)

In [ ]:
# 3. einsum for Complex Tensor Math
# Equivalent to batched matmul, but more readable for complex patterns
output_einsum = torch.einsum('bqd,bkd->bqk', Q, K) / 8.0

# Cross-correlation style convolution pattern
# 'ncwh,nckw->nkh' could represent depthwise ops, feature fusion, etc.

In [ ]:
# 4. Masking & Padding Handling
seq_len = 10
batch_size = 4
vocab_size = 1000

logits = torch.randn(batch_size, seq_len, vocab_size)

# Attention mask: True = keep, False = ignore
mask = torch.ones(batch_size, seq_len).bool()
mask[:, 7:] = False  # Pad tokens 7-9

# Apply mask: set ignored positions to -inf before softmax
logits = logits.masked_fill(~mask.unsqueeze(-1), float('-inf'))
probs = torch.softmax(logits, dim=-1)

In [ ]:
# 5. Indexing & Dynamic Routing
# Lookup embeddings for a batch of token IDs
token_ids = torch.tensor([[10, 52, 99],
                          [33, 10, 42]])  # (2, 3)
embeddings = torch.randn(1000, 128)      # (vocab, dim)

token_embeds = embeddings[token_ids]     # → (2, 3, 128)

In [ ]:
# Framework Syntax Comparison (PyTorch vs TensorFlow vs JAX)

# This is a quick "cheat sheet" for common tensor ops.
# (JAX examples are shown as code strings so this cell runs even if jax isn't installed.)

import torch
import tensorflow as tf

print("Create:")
print("  PyTorch     : torch.tensor([...])")
print("  TensorFlow  : tf.constant([...])")
print("  JAX         : jnp.array([...])")

print("\nReshape:")
print("  PyTorch     : x.view(...)   or x.reshape(...)")
print("  TensorFlow  : tf.reshape(x, ...) ")
print("  JAX         : jnp.reshape(x, ...)")

print("\nPermute / Transpose:")
print("  PyTorch     : x.permute(dims)")
print("  TensorFlow  : tf.transpose(x, perm=...)")
print("  JAX         : jnp.transpose(x, axes=...)")

print("\nBatch MatMul:")
print("  PyTorch     : torch.bmm(A, B)   or A @ B")
print("  TensorFlow  : tf.matmul(A, B)")
print("  JAX         : jnp.matmul(A, B)")

print("\nEinsum:")
print("  PyTorch     : torch.einsum('bik,bkj->bij', A, B)")
print("  TensorFlow  : tf.einsum('bik,bkj->bij', A, B)")
print("  JAX         : jnp.einsum('bik,bkj->bij', A, B)")

print("\nGather / Take:")
print("  PyTorch     : x.gather(dim, indices)   or x[indices]")
print("  TensorFlow  : tf.gather(x, indices, axis=...)")
print("  JAX         : jnp.take(x, indices, axis=...)")

print("\nNote: All support autograd and device placement.")
print("  PyTorch: x.to('cuda')  |  TF: tf.device(...)  |  JAX: jit/vmap/pmap")


In [ ]:
# Performance & Best Practices (Practical Tips)

import torch

# 1) Contiguous memory (PyTorch)
# After permute, memory layout changes. Call .contiguous() before view() in many cases.
X = torch.randn(2, 3, 4)
Xp = X.permute(0, 2, 1)           # not contiguous
print("is_contiguous before:", Xp.is_contiguous())

Xp2 = Xp.contiguous().view(2, -1) # safe
print("view after contiguous shape:", Xp2.shape)

# 2) In-place vs out-of-place
# In-place ops can save memory but can break autograd if misused.
y = torch.randn(5, requires_grad=True)
loss = (y * y).sum()
loss.backward()
print("grad ok:", y.grad.shape)

# 3) Dimension order matters (NCHW vs NHWC)
# PyTorch convs typically prefer NCHW: (batch, channels, height, width)
images_nchw = torch.randn(32, 3, 28, 28)
print("NCHW shape:", images_nchw.shape)

# 4) Avoid Python loops over tensor dims
# Example: sum over last dim (vectorized)
A = torch.randn(1024, 512)
col_sum = A.sum(dim=0)
print("col_sum shape:", col_sum.shape)

# 5) Prefer fused/optimized ops when available
# Example: linear layer uses a fused matmul + bias inside torch.nn.functional.linear
import torch.nn.functional as F
W = torch.randn(128, 512)
b = torch.randn(128)
x = torch.randn(32, 512)
out = F.linear(x, W, b)
print("linear output shape:", out.shape)
