Intro to Linear Algebra
This topic, Intro to Linear Algebra, is the first in the Machine Learning Foundations series.

The content covered in Intro to Linear Algebra is itself foundational for all the other topics in the Machine Learning Foundations series and it is especially relevant to Linear Algebra I.

Data Structures for Algebra

Linear Algebra:
- Scalars
- Vectors
- Matrices
- Tensors

Import Libraries

In [1]:
import numpy as np
import torch as th
import tensorflow as tf
import math

Scalars (Rank 0 Tensors) in Base Python

In [2]:
x = 5 # if we need more specificity (e.g., int16, uint8), we use NumPy or another numeric lib
y = 2.5
z = -10

In [8]:
print(x)
print(type(x))

print(y)
print(type(y))

print(z)
print(type(z))

5
<class 'int'>
2.5
<class 'float'>
-10
<class 'int'>


Scalars in PyTorch

- PyTorch and TensorFlow are the two most popular automatic differentiation libraries in Python, itself the most popular programming language in ML.

- PyTorch tensors are designed to be pythonic, i.e., to feel and behave like NumPy arrays.

- The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU (see here for example).

In [4]:
x = th.tensor(5) # type specification optional, e.g.: dtype=th.float16
y = th.tensor(2.5)

In [6]:
print(x)
print(x.ndim)   # number of dimensions
print(x.shape)  # shape of scalar
print("----------")
print(y)
print(y.ndim)
print(y.shape)

tensor(5)
0
torch.Size([])
----------
tensor(2.5000)
0
torch.Size([])


Scalars in TensorFlow

- As with TF tensors, in PyTorch we can similarly perform operations, and we can easily convert to and from NumPy arrays.

In [7]:
x = tf.constant(5)
y = tf.constant(2.5)

In [8]:
print(x)
print(tf.rank(x))
print(x.shape)
print("-----------")
print(y)
print(tf.rank(y))
print(y.shape)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
()
-----------
tf.Tensor(2.5, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)
()


Tiny practical example

In [13]:
# Base Python
loss = 0.128
print(loss)

0.128


In [15]:
# PyTorch
loss = th.tensor(0.128)
print(loss)
print(loss.ndim)

tensor(0.1280)
0


In [16]:
#TensorFlow
loss = tf.constant(0.128)
print(loss)
print(tf.rank(loss))

tf.Tensor(0.128, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)


Vectors (Rank 1 Tensors) - A vector is an ordered list of numbers.

In [9]:
v = [1, 2, 3]

# Base Python
print(v)
print(type(v))
print(len(v))  # number of elements

[1, 2, 3]
<class 'list'>
3


NumPy vector

In [10]:
v = np.array([1, 2, 3])

# NumPy vector
print(v)
print(v.shape)   # dimensions
print(v.ndim)    # rank

[1 2 3]
(3,)
1


PyTorch vector

In [11]:
v = th.tensor([1, 2, 3])

# PyTorch vector
print(v)
print(v.shape)
print(v.ndim)

tensor([1, 2, 3])
torch.Size([3])
1


TensorFlow vector

In [12]:
v = tf.constant([1, 2, 3])

# TensorFlow vector
print(v)
print(tf.rank(v))
print(v.shape)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
(3,)


Tiny practical example (ML)
Features of one house: [size, rooms, age] = [120, 3, 10]

In [13]:
# NumPy vector
np_house = np.array([120, 3, 10])
print(np_house)

# PyTorch vector
th_house = th.tensor([120, 3, 10])
print(th_house)

# TensorFlow vector
tf_house = tf.constant([120, 3, 10])
print(tf_house)


[120   3  10]
tensor([120,   3,  10])
tf.Tensor([120   3  10], shape=(3,), dtype=int32)
