Intro to Linear Algebra
This topic, Intro to Linear Algebra, is the first in the Machine Learning Foundations series.

The content covered in Intro to Linear Algebra is itself foundational for all the other topics in the Machine Learning Foundations series and it is especially relevant to Linear Algebra I.

Data Structures for Algebra

What Linear Algebra Is
A Brief History of Algebra
Tensors
Scalars
Vectors and Vector Transposition
Norms and Unit Vectors
Basis, Orthogonal, and Orthonormal Vectors
Arrays in NumPy
Matrices
Tensors in TensorFlow and PyTorch
Segment 2: Common Tensor Operations

Tensor Transposition
Basic Tensor Arithmetic
Reduction
The Dot Product
Solving Linear Systems
Segment 3: Matrix Properties

The Frobenius Norm
Matrix Multiplication
Symmetric and Identity Matrices
Matrix Inversion
Diagonal Matrices
Orthogonal Matrices

What Linear Algebra Is
Scalars
Vectors and Vector Transposition
Norms and Unit Vectors
Basis, Orthogonal, and Orthonormal Vectors
Arrays in NumPy
Matrices
Tensors in TensorFlow and PyTorch
Common Tensor Operations

Tensor Transposition
Basic Tensor Arithmetic
Reduction
The Dot Product
Solving Linear Systems
Segment 3: Matrix Properties

The Frobenius Norm
Matrix Multiplication
Symmetric and Identity Matrices
Matrix Inversion
Diagonal Matrices
Orthogonal Matrices

Data Structures for Algebra:
- Tensors
- Scalars
- Vectors and Vector Transposition
- Norms and Unit Vectors
- Basis, Orthogonal, and Orthonormal Vectors
- Arrays in NumPy
- Matrices
- Tensors in TensorFlow and PyTorch

Common Tensor Operations:
- Tensor Transposition
- Basic Tensor Arithmetic
- Reduction
- The Dot Product
- Solving Linear Systems


Matrix Properties:
- The Frobenius Norm
- Matrix Multiplication
- Symmetric and Identity Matrices
- Matrix Inversion
- Diagonal Matrices
- Orthogonal Matrices

Import Libraries

In [2]:
import numpy as np
import torch as th
import tensorflow as tf
import math

Scalars (Rank 0 Tensors) in Base Python

In [7]:
x = 5 # if we need more specificity (e.g., int16, uint8), we use NumPy or another numeric lib
y = 2.5
z = -10

In [8]:
print(x)
print(type(x))

print(y)
print(type(y))

print(z)
print(type(z))

5
<class 'int'>
2.5
<class 'float'>
-10
<class 'int'>


Scalars in PyTorch

- PyTorch and TensorFlow are the two most popular automatic differentiation libraries in Python, itself the most popular programming language in ML.

- PyTorch tensors are designed to be pythonic, i.e., to feel and behave like NumPy arrays.

- The advantage of PyTorch tensors relative to NumPy arrays is that they easily be used for operations on GPU (see here for example).

In [6]:
x = th.tensor(5) # type specification optional, e.g.: dtype=th.float16
y = th.tensor(2.5)

In [10]:
print(x)
print(x.ndim)   # number of dimensions
print(x.shape)  # shape of scalar

print(y)
print(y.ndim)
print(y.shape)

tensor(5)
0
torch.Size([])
tensor(2.5000)
0
torch.Size([])


Scalars in TensorFlow

- As with TF tensors, in PyTorch we can similarly perform operations, and we can easily convert to and from NumPy arrays.

In [5]:
x = tf.constant(5)
y = tf.constant(2.5)

In [12]:
print(x)
print(tf.rank(x))
print(x.shape)

print(y)
print(tf.rank(y))
print(y.shape)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
()
tf.Tensor(2.5, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)
()


Tiny practical example

In [13]:
# Base Python
loss = 0.128
print(loss)

0.128


In [15]:
# PyTorch
loss = th.tensor(0.128)
print(loss)
print(loss.ndim)

tensor(0.1280)
0


In [16]:
#TensorFlow
loss = tf.constant(0.128)
print(loss)
print(tf.rank(loss))

tf.Tensor(0.128, shape=(), dtype=float32)
tf.Tensor(0, shape=(), dtype=int32)


Vectors (Rank 1 Tensors) - A vector is an ordered list of numbers.

In [7]:
v = [1, 2, 3]

# Base Python
print(v)
print(type(v))
print(len(v))  # number of elements

[1, 2, 3]
<class 'list'>
3


NumPy vector

In [ ]:
v = np.array([1, 2, 3])

# NumPy vector
print(v)
print(v.shape)   # dimensions
print(v.ndim)    # rank

[1 2 3]
(3,)
1


PyTorch vector

In [8]:
v = th.tensor([1, 2, 3])

# PyTorch vector
print(v)
print(v.shape)
print(v.ndim)

tensor([1, 2, 3])
torch.Size([3])
1


TensorFlow vector

In [9]:
v = tf.constant([1, 2, 3])

# TensorFlow vector
print(v)
print(tf.rank(v))
print(v.shape)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
(3,)


Tiny practical example (ML)
Features of one house: [size, rooms, age] = [120, 3, 10]

In [14]:
# NumPy vector
np_house = np.array([120, 3, 10])
print(np_house)

# PyTorch vector
th_house = th.tensor([120, 3, 10])
print(th_house)

# TensorFlow vector
tf_house = tf.constant([120, 3, 10])
print(tf_house)


[120   3  10]
tensor([120,   3,  10])
tf.Tensor([120   3  10], shape=(3,), dtype=int32)


Norms - A norm = length (magnitude) of a vector
It answers: “How big is this vector?”
• L2 → sqrt of squares
• L1 → sum of absolute values
• L∞ → max absolute value

Base Python (manual)

In [24]:
v = [3, 4]

l2 = math.sqrt(sum(x**2 for x in v))
l1 = sum(abs(x) for x in v)
linf = max(abs(x) for x in v)

print(l2)   # 5.0
print(l1)   # 7
print(linf) # 4

5.0
7
4


NumPy

In [25]:
v = np.array([3, 4])

print(np.linalg.norm(v))        # L2
print(np.linalg.norm(v, ord=1)) # L1
print(np.linalg.norm(v, ord=np.inf)) # L∞

5.0
7.0
4.0


PyTorch

In [26]:
v = torch.tensor([3.0, 4.0])

print(torch.norm(v, p=2))      # L2
print(torch.norm(v, p=1))      # L1
print(torch.norm(v, p=float('inf')))  # L∞

tensor(5.)
tensor(7.)
tensor(4.)


TensorFlow

In [27]:
v = tf.constant([3.0, 4.0])

print(tf.norm(v, ord=2))        # L2
print(tf.norm(v, ord=1))        # L1
print(tf.norm(v, ord=float('inf')))  # L∞

tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(7.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)


Squared L2 Norm A Squared L2 Norm = sum of squares of vector elements (no square root)

In [29]:
l2 = [3, 4]
l2_np = np.array([3, 4], dtype=np.float32)
l2_th = th.tensor([3, 4], dtype=th.float32)
l2_tf = tf.constant([3, 4], dtype=tf.float32)

# Base Python
squared_l2 = sum(x**2 for x in l2)
print(squared_l2)  # 25

# NumPy
print(np.linalg.norm(l2_np)**2)
print(np.sum(l2_np**2))
print(np.dot(l2_np, l2_np))

# PyTorch
print(th.norm(l2_th)**2)
print(th.sum(l2_th**2))
print(th.dot(l2_th, l2_th))

# TensorFlow
print(tf.norm(l2_tf)**2)
print(tf.reduce_sum(l2_tf**2))
print(tf.tensordot(l2_tf, l2_tf, axes=1))


25
25.0
25.0
25.0
tensor(25.)
tensor(25.)
tensor(25.)
tf.Tensor(25.0, shape=(), dtype=float32)
tf.Tensor(25.0, shape=(), dtype=float32)
tf.Tensor(25.0, shape=(), dtype=float32)


Basis, Orthogonal, and Orthonormal Vectors
Basis - A basis = a set of vectors that can build (represent) any vector in a space.
Standard basis: e1 = [1, 0] | e2 = [0, 1]
Any vector: v = [3, 4] = 3·e1 + 4·e2

Orthogonal Vectors - Two vectors are orthogonal if they are perpendicular
Condition: v⋅w = 0Example: v = [1, 0]  | w = [0, 1]
Dot product:  1*0 + 0*1 = 0 → orthogonal

Orthonormal Vectors -  orthogonal (perpendicular) AND each vector has norm = 1Example: v = [1, 0]  | w = [0, 1]
dot = 0 → orthogonal → norm = 1 → unit  → orthonormal

Tiny ML connection
Orthonormal vectors → used in embeddings, PCA
Basis → feature representation
Orthogonality → reduces redundancy

In [ ]:
# NumPy
v = np.array([1, 0])
w = np.array([0, 1])

# dot product
dot = np.dot(v, w)

# norms
norm_v = np.linalg.norm(v)
norm_w = np.linalg.norm(w)

print(dot)     # 0 → orthogonal
print(norm_v)  # 1
print(norm_w)  # 1

0
1.0
1.0


In [4]:
# PyTorch
v = th.tensor([1.0, 0.0])
w = th.tensor([0.0, 1.0])

dot = th.dot(v, w)
norm_v = th.norm(v)
norm_w = th.norm(w)

print(dot)
print(norm_v)
print(norm_w)

tensor(0.)
tensor(1.)
tensor(1.)


In [5]:
# TensorFlow
v = tf.constant([1.0, 0.0])
w = tf.constant([0.0, 1.0])

dot = tf.tensordot(v, w, axes=1)
norm_v = tf.norm(v)
norm_w = tf.norm(w)

print(dot)
print(norm_v)
print(norm_w)

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


Vector Operations (addition, scalar multiplication, dot product).

Vector Addition - Add vectors element-wise
v = [1, 2]
w = [3, 4]
v + w = [4, 6]

Scalar Multiplication - Multiply each element by a number
v = [1, 2]
k = 3
k * v = [3, 6]

Dot Product (very important) - Multiply elements → then sum

Formula: V ⋅ W = X1 Y1 +X2 Y2 + … + Xn Yn
v = [1, 2]
w = [3, 4]

1 * 3 + 2 * 4 = 3 + 8 = 11

Meaning
* measures similarity
* if result = 0 → orthogonal
* larger → more aligned

In [6]:
# Base Python
v = [1, 2]
w = [3, 4]

dot = sum(v[i] * w[i] for i in range(len(v)))
print(dot)

# NumPy
v = np.array([1, 2])
w = np.array([3, 4])

dot = np.dot(v, w)
print(dot)

# PyTorch
v = th.tensor([1, 2])
w = th.tensor([3, 4])

dot = th.dot(v, w)
print(dot)

# TensorFlow
v = tf.constant([1, 2])
w = tf.constant([3, 4])

dot = tf.tensordot(v, w, axes=1)
print(dot)

11
11
tensor(11)
tf.Tensor(11, shape=(), dtype=int32)


Matrix / Tensor (foundations)
1) Matrix - A matrix = 2D array of numbers (rows × columns)

Example:
A = [
  [1, 2, 3],
  [4, 5, 6]
]

Shape: 2 rows × 3 columns → (2, 3)Meaning:
- each row → one object
- each column → one feature

Human example Students:
[
  [20, 175, 70],
  [22, 180, 80]
]

row = student
columns = [age, height, weight]

In [8]:
# Base Python
bsp_A = [
    [1, 2, 3],
    [4, 5, 6]
]

print(bsp_A)
print(len(bsp_A))        # rows
print(len(bsp_A[0]))     # columns

# NumPy
np_A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(np_A)
print(np_A.shape)
print(np_A.ndim)

# PyTorch
th_A = th.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print(th_A)
print(th_A.shape)
print(th_A.ndim)

# TensorFlow
tf_A = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

print(tf_A)
print(tf_A.shape)
print(tf_A.ndim)

# PyTorch
th_A = th.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

[[1, 2, 3], [4, 5, 6]]
2
3
[[1 2 3]
 [4 5 6]]
(2, 3)
2
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
2
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
2


In [9]:
# 3D Tensor example (important for AI)

# NumPy
np_T = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

print(np_T.shape)  # (2,2,2)

# PyTorch
th_T = th.tensor([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

print(th_T.shape)  # (2,2,2)

# TensorFlow
tf_T = tf.constant([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

print(tf_T.shape)  # (2,2,2)


(2, 2, 2)
torch.Size([2, 2, 2])
(2, 2, 2)
